### ISSUE TITLE
String-Util-1.33 fails to build

### ISSUE THREAD

**Issue by sh3p4rd** [scottchiefbaker/String-Util#5]
Step to replicate:

1. `cpanm String::Util`

It seems like this commit solves the problem: https://github.com/gitpan/String-Util/commit/299e40d9112c351309963d3d1462fd14d13e4a63

**Comment by scottchiefbaker** [comment]
This was a silly mistake on my part. I release v1.34 about 30 minutes ago and it fixes this problem. Please try installing again from cpam, it should work now.

http://fast-matrix.cpantesters.org/?dist=String-Util
