### ISSUE TITLE
String-util doesn't build with perl 5.30 

### ISSUE THREAD

**Issue by Naeem-Akhter** [scottchiefbaker/String-Util#6]
Please have a look at build failure at bottom. 
Perl Version : 5.30 
OS : Ubuntu: 20.04  

Can you please fix it or suggest workaround? 

---------------------------------------------
yes | sudo /usr/bin/perl -MCPAN -e 'install String::Util'
Reading '/root/.cpan/Metadata'
  Database was generated on Wed, 01 Feb 2023 11:41:01 GMT
Running install for module 'String::Util'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/B/BA/BAKERSCOT/String-Util-1.33.tar.gz
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/B/BA/BAKERSCOT/CHECKSUMS
Checksum for /root/.cpan/sources/authors/id/B/BA/BAKERSCOT/String-Util-1.33.tar.gz ok
'YAML' not installed, will not store persistent state
  Warning: CPAN.pm discovered Module::Build as undeclared prerequisite.
  Adding it now as such.
---- Unsatisfied dependencies detected during ----
----     BAKERSCOT/String-Util-1.33.tar.gz    ----
    Module::Build [build_requires]
    Module::Build::Tiny [build_requires]
Running install for module 'Module::Build'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/L/LE/LEONT/Module-Build-0.4232.tar.gz
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/L/LE/LEONT/CHECKSUMS
Checksum for /root/.cpan/sources/authors/id/L/LE/LEONT/Module-Build-0.4232.tar.gz ok
Configuring L/LE/LEONT/Module-Build-0.4232.tar.gz with Makefile.PL

Checking optional features...
inc_bundling_support....disabled
  requires:
    ! inc::latest is not installed
ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
of the modules indicated above before proceeding with this installation
Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Module-Build' version '0.4232'
  LEONT/Module-Build-0.4232.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for L/LE/LEONT/Module-Build-0.4232.tar.gz
/usr/bin/perl Build --makefile_env_macros 1
Building Module-Build
  LEONT/Module-Build-0.4232.tar.gz
  /usr/bin/make -- OK
Running make test for LEONT/Module-Build-0.4232.tar.gz
/usr/bin/perl Build --makefile_env_macros 1 test
t/00-compile.t ................. ok
t/PL_files.t ................... ok
t/actions/installdeps.t ........ ok
t/actions/manifest_skip.t ...... ok
t/add_property.t ............... ok
t/add_property_array.t ......... ok
t/add_property_hash.t .......... ok
t/basic.t ...................... ok
t/bundle_inc.t ................. skipped: $ENV{MB_TEST_EXPERIMENTAL} is not set
t/compat.t ..................... ok
t/compat/exit.t ................ ok
t/debug.t ...................... ok
t/destinations.t ............... ok
t/ext.t ........................ ok
t/extend.t ..................... ok
t/files.t ...................... ok
t/help.t ....................... ok
t/install.t .................... ok
t/install_extra_target.t ....... ok
t/manifypods.t ................. ok
t/manifypods_with_utf8.t ....... ok
t/metadata.t ................... ok
t/metadata2.t .................. ok
t/mymeta.t ..................... ok
t/new_from_context.t ........... ok
t/notes.t ...................... ok
t/par.t ........................ skipped: PAR::Dist 0.17 or up not installed to check .par's.
t/parents.t .................... ok
t/perl_mb_opt.t ................ ok
t/pod_parser.t ................. ok
t/ppm.t ........................ ok
t/properties/dist_suffix.t ..... ok
t/properties/license.t ......... ok
t/properties/module_name.t ..... ok
t/properties/needs_compiler.t .. ok
t/properties/release_status.t .. ok
t/properties/requires.t ........ ok
t/properties/share_dir.t ....... ok
t/resume.t ..................... ok
t/runthrough.t ................. ok
t/sample.t ..................... ok
t/script_dist.t ................ ok
t/signature.t .................. ok
t/test_file_exts.t ............. ok
t/test_reqs.t .................. ok
t/test_type.t .................. ok
t/test_types.t ................. ok
t/tilde.t ...................... ok
t/unit_run_test_harness.t ...... ok
t/use_tap_harness.t ............ ok
t/versions.t ................... ok
t/write_default_maniskip.t ..... ok
t/xs.t ......................... ok
All tests successful.
Files=53, Tests=1167, 32 wallclock secs ( 0.18 usr  0.02 sys + 27.89 cusr  3.84 csys = 31.93 CPU)
Result: PASS
  LEONT/Module-Build-0.4232.tar.gz
  /usr/bin/make test -- OK
Running make install for LEONT/Module-Build-0.4232.tar.gz
/usr/bin/perl Build --makefile_env_macros 1 install
Building Module-Build
Installing /usr/local/man/man1/config_data.1p
Installing /usr/local/share/perl/5.30.0/Module/Build.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/PPMMaker.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Cookbook.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/ConfigData.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Authoring.pod
Installing /usr/local/share/perl/5.30.0/Module/Build/Compat.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Notes.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/PodParser.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/API.pod
Installing /usr/local/share/perl/5.30.0/Module/Build/Dumper.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Bundling.pod
Installing /usr/local/share/perl/5.30.0/Module/Build/Config.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Base.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Platform/Windows.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Platform/aix.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Platform/VMS.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Platform/Unix.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Platform/cygwin.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Platform/VOS.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Platform/os2.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Platform/darwin.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Platform/Default.pm
Installing /usr/local/share/perl/5.30.0/Module/Build/Platform/MacOS.pm
Installing /usr/local/man/man3/Module::Build::ConfigData.3pm
Installing /usr/local/man/man3/Module::Build::Base.3pm
Installing /usr/local/man/man3/Module::Build::Platform::Unix.3pm
Installing /usr/local/man/man3/Module::Build::Platform::Default.3pm
Installing /usr/local/man/man3/Module::Build::Platform::Windows.3pm
Installing /usr/local/man/man3/Module::Build::Compat.3pm
Installing /usr/local/man/man3/Module::Build::Notes.3pm
Installing /usr/local/man/man3/Module::Build::Platform::VMS.3pm
Installing /usr/local/man/man3/Module::Build::Platform::VOS.3pm
Installing /usr/local/man/man3/Module::Build.3pm
Installing /usr/local/man/man3/Module::Build::Platform::cygwin.3pm
Installing /usr/local/man/man3/Module::Build::Platform::darwin.3pm
Installing /usr/local/man/man3/Module::Build::Bundling.3pm
Installing /usr/local/man/man3/Module::Build::Platform::os2.3pm
Installing /usr/local/man/man3/Module::Build::Cookbook.3pm
Installing /usr/local/man/man3/Module::Build::API.3pm
Installing /usr/local/man/man3/Module::Build::PPMMaker.3pm
Installing /usr/local/man/man3/Module::Build::Platform::aix.3pm
Installing /usr/local/man/man3/Module::Build::Platform::MacOS.3pm
Installing /usr/local/man/man3/Module::Build::Authoring.3pm
Installing /usr/local/bin/config_data
  LEONT/Module-Build-0.4232.tar.gz
  /usr/bin/make install  -- OK
Running install for module 'Module::Build::Tiny'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz
Checksum for /root/.cpan/sources/authors/id/L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz ok
---- Unsatisfied dependencies detected during ----
----   LEONT/Module-Build-Tiny-0.039.tar.gz   ----
    ExtUtils::Config [build_requires]
    ExtUtils::Helpers [build_requires]
    ExtUtils::InstallPaths [build_requires]
Running install for module 'ExtUtils::Config'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/L/LE/LEONT/ExtUtils-Config-0.008.tar.gz
Checksum for /root/.cpan/sources/authors/id/L/LE/LEONT/ExtUtils-Config-0.008.tar.gz ok
Configuring L/LE/LEONT/ExtUtils-Config-0.008.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for ExtUtils::Config
Writing MYMETA.yml and MYMETA.json
  LEONT/ExtUtils-Config-0.008.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for L/LE/LEONT/ExtUtils-Config-0.008.tar.gz
cp lib/ExtUtils/Config.pm blib/lib/ExtUtils/Config.pm
Manifying 1 pod document
  LEONT/ExtUtils-Config-0.008.tar.gz
  /usr/bin/make -- OK
Running make test for LEONT/ExtUtils-Config-0.008.tar.gz
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-compile.t ............ ok
t/basics.t ................ ok
t/release-pod-coverage.t .. skipped: these tests are for release candidate testing
t/release-pod-syntax.t .... skipped: these tests are for release candidate testing
All tests successful.
Files=4, Tests=9,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.18 cusr  0.03 csys =  0.23 CPU)
Result: PASS
  LEONT/ExtUtils-Config-0.008.tar.gz
  /usr/bin/make test -- OK
Running make install for LEONT/ExtUtils-Config-0.008.tar.gz
Manifying 1 pod document
Installing /usr/local/share/perl/5.30.0/ExtUtils/Config.pm
Installing /usr/local/man/man3/ExtUtils::Config.3pm
Appending installation info to /usr/local/lib/x86_64-linux-gnu/perl/5.30.0/perllocal.pod
  LEONT/ExtUtils-Config-0.008.tar.gz
  /usr/bin/make install  -- OK
Running install for module 'ExtUtils::Helpers'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz
Checksum for /root/.cpan/sources/authors/id/L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz ok
Configuring L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for ExtUtils::Helpers
Writing MYMETA.yml and MYMETA.json
  LEONT/ExtUtils-Helpers-0.026.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for L/LE/LEONT/ExtUtils-Helpers-0.026.tar.gz
cp lib/ExtUtils/Helpers/Unix.pm blib/lib/ExtUtils/Helpers/Unix.pm
cp lib/ExtUtils/Helpers.pm blib/lib/ExtUtils/Helpers.pm
cp lib/ExtUtils/Helpers/Windows.pm blib/lib/ExtUtils/Helpers/Windows.pm
cp lib/ExtUtils/Helpers/VMS.pm blib/lib/ExtUtils/Helpers/VMS.pm
Manifying 4 pod documents
  LEONT/ExtUtils-Helpers-0.026.tar.gz
  /usr/bin/make -- OK
Running make test for LEONT/ExtUtils-Helpers-0.026.tar.gz
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/make_executable.t ... ok
t/man_pagename.t ...... ok
t/split_like_shell.t .. ok
t/tilde.t ............. ok
All tests successful.
Files=4, Tests=30,  0 wallclock secs ( 0.01 usr  0.02 sys +  0.21 cusr  0.01 csys =  0.25 CPU)
Result: PASS
  LEONT/ExtUtils-Helpers-0.026.tar.gz
  /usr/bin/make test -- OK
Running make install for LEONT/ExtUtils-Helpers-0.026.tar.gz
Manifying 4 pod documents
Installing /usr/local/share/perl/5.30.0/ExtUtils/Helpers.pm
Installing /usr/local/share/perl/5.30.0/ExtUtils/Helpers/Windows.pm
Installing /usr/local/share/perl/5.30.0/ExtUtils/Helpers/VMS.pm
Installing /usr/local/share/perl/5.30.0/ExtUtils/Helpers/Unix.pm
Installing /usr/local/man/man3/ExtUtils::Helpers.3pm
Installing /usr/local/man/man3/ExtUtils::Helpers::Windows.3pm
Installing /usr/local/man/man3/ExtUtils::Helpers::VMS.3pm
Installing /usr/local/man/man3/ExtUtils::Helpers::Unix.3pm
Appending installation info to /usr/local/lib/x86_64-linux-gnu/perl/5.30.0/perllocal.pod
  LEONT/ExtUtils-Helpers-0.026.tar.gz
  /usr/bin/make install  -- OK
Running install for module 'ExtUtils::InstallPaths'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz
Checksum for /root/.cpan/sources/authors/id/L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz ok
Configuring L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for ExtUtils::InstallPaths
Writing MYMETA.yml and MYMETA.json
  LEONT/ExtUtils-InstallPaths-0.012.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for L/LE/LEONT/ExtUtils-InstallPaths-0.012.tar.gz
cp lib/ExtUtils/InstallPaths.pm blib/lib/ExtUtils/InstallPaths.pm
Manifying 1 pod document
  LEONT/ExtUtils-InstallPaths-0.012.tar.gz
  /usr/bin/make -- OK
Running make test for LEONT/ExtUtils-InstallPaths-0.012.tar.gz
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/destinations.t .. ok
All tests successful.
Files=1, Tests=111,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.05 cusr  0.01 csys =  0.08 CPU)
Result: PASS
  LEONT/ExtUtils-InstallPaths-0.012.tar.gz
  /usr/bin/make test -- OK
Running make install for LEONT/ExtUtils-InstallPaths-0.012.tar.gz
Manifying 1 pod document
Installing /usr/local/share/perl/5.30.0/ExtUtils/InstallPaths.pm
Installing /usr/local/man/man3/ExtUtils::InstallPaths.3pm
Appending installation info to /usr/local/lib/x86_64-linux-gnu/perl/5.30.0/perllocal.pod
  LEONT/ExtUtils-InstallPaths-0.012.tar.gz
  /usr/bin/make install  -- OK
  LEONT/Module-Build-Tiny-0.039.tar.gz
  Has already been unwrapped into directory /root/.cpan/build/Module-Build-Tiny-0.039-0
Configuring L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz with Build.PL
Creating new 'Build' script for 'Module-Build-Tiny' version '0.039'
  LEONT/Module-Build-Tiny-0.039.tar.gz
  /usr/bin/perl Build.PL --installdirs site -- OK
Running Build for L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz
cp lib/Module/Build/Tiny.pm blib/lib/Module/Build/Tiny.pm
  LEONT/Module-Build-Tiny-0.039.tar.gz
  ./Build -- OK
Running Build test for LEONT/Module-Build-Tiny-0.039.tar.gz
t/00-compile.t .......... ok
t/release-pod-syntax.t .. skipped: these tests are for release candidate testing
t/simple.t .............. ok
All tests successful.
Files=3, Tests=26,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.33 cusr  0.02 csys =  0.37 CPU)
Result: PASS
  LEONT/Module-Build-Tiny-0.039.tar.gz
  ./Build test -- OK
Running Build install for LEONT/Module-Build-Tiny-0.039.tar.gz
Installing /usr/local/share/perl/5.30.0/Module/Build/Tiny.pm
Installing /usr/local/man/man3/Module::Build::Tiny.3pm
  LEONT/Module-Build-Tiny-0.039.tar.gz
  ./Build install  -- OK
  BAKERSCOT/String-Util-1.33.tar.gz
  Has already been unwrapped into directory /root/.cpan/build/String-Util-1.33-0
**Configuring B/BA/BAKERSCOT/String-Util-1.33.tar.gz with Build.PL
Perl v5.140.0 required (did you mean v5.14.0?)--this is only v5.30.0, stopped at Build.PL line 5.
BEGIN failed--compilation aborted at Build.PL line 5.
Warning: No success on command[/usr/bin/perl Build.PL --installdirs site]
  BAKERSCOT/String-Util-1.33.tar.gz
  /usr/bin/perl Build.PL --installdirs site -- NOT OK**

**Comment by scottchiefbaker** [comment]
This is the same issue as #5. The just release v1.34 should solve this problem for you.

http://fast-matrix.cpantesters.org/?dist=String-Util
